feat: toasts
decentraland/ui pull request #107
Opened 2021-05-28 20:43 UTC by nicosantangelo

Examples:
<img width="466" alt="image" src="https://user-images.githubusercontent.com/692077/120039956-23d7fd00-bfdc-11eb-99ba-53db8a37733f.png">
<img width="654" alt="image" src="https://user-images.githubusercontent.com/692077/120039961-25a1c080-bfdc-11eb-9e3f-842f66182f79.png">

It's functional, but we're working on some improvements for a later version

2021-05-28 20:53 UTC, cazala requested changes

2021-05-31 15:47 UTC, nicosantangelo commented on src/components/Toast/Toast.tsx
> +export class Toast extends React.PureComponent<Props> {
@cazala Should we export ToastType from here?

2021-05-31 15:48 UTC, nicosantangelo commented on src/components/Toasts/Toasts.tsx
> +export default class Toasts extends React.PureComponent<Props> {
@cazala Should we export ToastPosition from here?, to be able to import it from the root package (`decentraland-ui`)

2021-05-31 16:07 UTC, nicosantangelo commented on src/components/Toast/Toast.tsx
> +    this.props.onClose()
I fixed this! but I was thinking, maybe this logic should be delegated to the user of the lib? (decentraland-dapps in our case)

I'm not sure, as maybe someone using just dcl-ui might want this behaviour, but I thought I ask

2021-05-31 17:15 UTC, cazala approved these changes

2021-05-31 17:16 UTC, merged

2021-05-31 17:18 UTC, cazala commented
:tada: This PR is included in version 3.5.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/decentraland-ui)
- [GitHub release](https://github.com/decentraland/ui/releases/tag/v3.5.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: