feat/make-dropdown-mobile-responsive
decentraland/ui pull request #253
Opened 2022-12-15 17:24 UTC by flobarreto

closes #211 
<img width="549" alt="image" src="https://user-images.githubusercontent.com/32873485/207926962-e660bb51-b723-40c2-9e1c-07d7c616b1e6.png">

2022-12-15 17:29 UTC, LautaroPetaccio requested changes

2022-12-15 17:29 UTC, LautaroPetaccio commented on src/components/Dropdown/Dropdown.tsx
> +}
Can we rewrite this so we export `DropdownProps` as the new type for everyone to use?
We'll need to import `DropdownProps` as `DropdownPropsSemanitc` to make it work.
```suggestion
export type DropdownProps = DropdownPropsSemanitc & {
 /* Mobile header title */
  title: string
}
```

2022-12-15 17:30 UTC, LautaroPetaccio requested changes

2022-12-15 17:30 UTC, LautaroPetaccio commented on src/components/Dropdown/Dropdown.tsx
> +        <Icon name="close" className="closeIcon" />
Isn't the X missing the functionality to close the dropdown?

2022-12-16 19:25 UTC, flobarreto commented
closed by design decision https://www.notion.so/decentraland/PRD-Rentals-04453e87b21c4e0db44932a06b28bf79#ac7140ce41de456f95a69d243f43164f

2022-12-16 19:25 UTC, closed without merging