feat: introduce the Chain selector component
decentraland/ui pull request #508
Opened 2024-02-07 14:01 UTC by juanmahidalgo

## standalone

### closed
![image](https://github.com/decentraland/ui/assets/8763687/fedd8393-d241-48db-bec1-9c1978982bbc)

### opened

![image](https://github.com/decentraland/ui/assets/8763687/8fe530f1-4cef-4fb7-8495-63507539a9fc)

## in navbar

### closed

![image](https://github.com/decentraland/ui/assets/8763687/e75f090a-f90e-4363-8f9e-4efc83d1be9b)

### opened (and switching to polygon in this example)

![image](https://github.com/decentraland/ui/assets/8763687/f44198ba-8184-4805-ab28-e15ef64f060d)

2024-02-07 15:35 UTC, cazala commented on src/components/ChainSelector/ChainSelector.tsx
> +              console.log('chain: ', chain)
oops console log

2024-02-07 15:45 UTC, cazala requested changes
On mobile we might want to make the button smaller, or perhaps only show the chain icon instead of icon + name, otherwise it overlaps with the DCL logo:

<img width="534" alt="Screenshot 2024-02-07 at 12 44 21" src="https://github.com/decentraland/ui/assets/2781777/6df195fa-bdf8-49c9-baef-c20738b9e615">

2024-02-08 10:18 UTC, juanmahidalgo commented
> On mobile we might want to make the button smaller, or perhaps only show the chain icon instead of icon + name, otherwise it overlaps with the DCL logo:
> 
> <img alt="Screenshot 2024-02-07 at 12 44 21" width="534" src="https://private-user-images.githubusercontent.com/2781777/303042764-6df195fa-bdf8-49c9-baef-c20738b9e615.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDczODY3NjYsIm5iZiI6MTcwNzM4NjQ2NiwicGF0aCI6Ii8yNzgxNzc3LzMwMzA0Mjc2NC02ZGYxOTVmYS1iZGY4LTQ5YzktYmFlZi1jMjA3MzhiOWU2MTUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIwOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMDhUMTAwMTA2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MzcwNzgwMGM4NjA1N2VjMzI0N2QxZWMwNGJjYjkxMWE4YzYyZTQzM2ZiYzU4NzAyZWNlZGMyMThiN2JmMDcyMiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.7lGISB2CKc2eHXKnDPe041SgZnerPqoYVbFRh3Ozlic">

Done!

<img width="371" alt="image" src="https://github.com/decentraland/ui/assets/8763687/b35a1cf2-dea5-48e6-949d-c13f65360ac2">

<img width="347" alt="image" src="https://github.com/decentraland/ui/assets/8763687/e565926a-ffd2-419d-a10e-2e6036df68e4">

2024-02-08 10:40 UTC, cazala approved these changes
🍏!

2024-02-13 12:20 UTC, cazala approved these changes

2024-02-13 13:13 UTC, merged